jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  timeoutInMinutes: 120
  variables:
    NUM_THREADS: 2
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      git lfs install
      git lfs fetch
      git lfs checkout
      pip install conan --upgrade
      conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      conan install ninja_installer/1.8.2_kitware@bincrafters/stable -r bincrafters -g=virtualenv
      call activate.bat
      mkdir build
      cd build
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\vsdevcmd" -arch=x64
      cmake .. -G Ninja -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DOGS_EIGEN_DYNAMIC_SHAPE_MATRICES=ON -DOGS_USE_PCH=OFF
      ninja -j 2 tests
      ninja -j 2 ctest
