[build]
  base    = "web"
  publish = "web/public"
  command = """
    yarn --ignore-engines --ignore-optional --non-interactive
    hugo
    node_modules/.bin/hugo-algolia --toml -s"""

[build.environment] # global variables
  HUGO_VERSION = "0.47.1"
  GIT_LFS_ENABLED = "true"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = """
    yarn --ignore-engines --ignore-optional --non-interactive
    hugo -b $DEPLOY_PRIME_URL"""

[context.branch-deploy]
  command = """
    yarn --ignore-engines --ignore-optional --non-interactive
    hugo -b $DEPLOY_PRIME_URL"""
