languageCode = "en-us"
title = "OpenGeoSys-6"
theme = "ogs"
baseURL = "http://localhost:1313"
buildDrafts = true
pygmentsstyle = 'friendly'
enableGitInfo = true

[params]
  alert = "Preliminary test page! Current documentation is at <a href='https://docs.opengeosys.org'>docs.opengeosys.org</a>."

[taxonomies]
news = "news"

# Main menu
[[menu.main]]
  name = "News"
  url = "/news/"
  weight = 1
# Menu entry defined in about.md
[[menu.main]]
  name = "Docs"
  url = "/docs/"
  identifier = "docs"
  weight = 3

# Devguide sidebar menu top-level categories
[[menu.devguide]]
  name = "Getting Started"
  identifier = "getting-started"

# Benchmarks sidebar top-level categories
[[menu.benchmarks]]
  name = "Elliptic"
  identifier = "elliptic"
  weight = 1
[[menu.benchmarks]]
  name = "Small Deformations"
  identifier = "small-deformations"
  weight = 2
[[menu.benchmarks]]
  name = "Heatconduction"
  identifier = "heatconduction"
  weight = 3
[[menu.benchmarks]]
  name = "Richards Flow"
  identifier = "richards-flow"
  weight = 4
[[menu.benchmarks]]
  name = "Hydro-Mechanics"
  identifier = "hydro-mechanics"
  weight = 5
