languageCode = "en-us"
title = "OpenGeoSys-6"
theme = "ogs"
baseURL = "https://www.opengeosys.org"
buildDrafts = false
buildFuture = true
pygmentsstyle = 'friendly'
enableGitInfo = true
canonifyURLs = true
staticDir = ["dist", "static"]

[params]
  alert = ""

# Main menu
[[menu.main]]
  name = "Books"
  url = "/books/"
  identifier = "books"
  weight = 2
[[menu.main]]
  name = "Releases"
  url = "/releases/"
  identifier = "releases"
  weight = 3
[[menu.main]]
  name = "Docs"
  url = "/docs/"
  identifier = "docs"
  weight = 4

[[menu.main]]
  name = "OpenGeoSys-5"
  url = "/ogs-5/"
  identifier = "ogs-5"
  weight = 5

# Devguide sidebar menu top-level categories
[[menu.devguide]]
  name = "Getting Started"
  identifier = "getting-started"
  weight = 1

[[menu.devguide]]
  name = "Development Workflows"
  identifier = "development-workflows"
  weight = 2

[[menu.devguide]]
  name = "Testing"
  identifier = "testing"
  weight = 3

[[menu.devguide]]
  name = "Advanced"
  identifier = "advanced"
  weight = 4

[[menu.devguide]]
  name = "Troubleshooting"
  identifier = "troubleshooting"
  weight = 5

[[menu.devguide]]
  name = "Procedures"
  identifier = "procedures"
  weight = 6

# Benchmarks sidebar top-level categories
[[menu.benchmarks]]
  name = "Elliptic"
  identifier = "elliptic"
  weight = 1
[[menu.benchmarks]]
  name = "Small Deformations"
  identifier = "small-deformations"
  weight = 2
[[menu.benchmarks]]
  name = "Heatconduction"
  identifier = "heatconduction"
  weight = 3
[[menu.benchmarks]]
  name = "Richards Flow"
  identifier = "richards-flow"
  weight = 4
[[menu.benchmarks]]
  name = "Hydro-Mechanics"
  identifier = "hydro-mechanics"
  weight = 5
[[menu.benchmarks]]
  name = "Hydro-Thermal"
  identifier = "hydro-thermal"
  weight = 6
[[menu.benchmarks]]
  name = "Liquid Flow"
  identifier = "liquid-flow"
  weight = 7
[[menu.benchmarks]]
  name = "Two-phase Flow"
  identifier = "two-phase-flow"
  weight = 8

# Quickstart sidebar top-level categories
[[menu.quickstart]]
  name = "Basics"
  identifier = "basics"
  weight = 1

# Tools sidebar top-level categories
[[menu.tools]]
  name = "Getting Started"
  identifier = "getting-started"
  weight = 1

[[menu.tools]]
  name = "Meshing"
  identifier = "meshing"
  weight = 2

[[menu.tools]]
  name = "Model Preparation"
  identifier = "model-preparation"
  weight = 3

[[menu.tools]]
  name = "Workflows"
  identifier = "workflows"
  weight = 4
