exclude = [
  "gitlab\\.opengeosys\\.org",
  "discourse\\.opengeosys\\.org",
  "vip\\.s3\\.ufz\\.de/ogs/public/binaries/ogs6",
  "discourse\\.opengeosys.org/t/",
  "localhost:1313",
  "smartkd-concept\\.de",
  "all\\.css",
  "eigen\\.tuxfamily.org",
  "www\\.ufz\\.de/vislab",
  "mont_terri_experimente.html",
  "coolprop\\.org",
  "www\\.gpdn\\.de",
  "gitlab\\.io",
  "overleaf\\.com",
]
exclude_path = ["public/releases/", "public/docs/featurematrix/bundle/"]
